App doc
coopcycle/coopcycle-docs pull request #10
Opened 2019-06-17 16:06 UTC by arnomasson

2019-06-17 16:13 UTC, alexsegura commented on fr/coursier/tache.md
> +Dès qu'une nouvelle tâche vous est assigné, vous recevez une notification sur votre téléphone.
`assigné` → `assignée`

2019-06-17 16:13 UTC, alexsegura commented on fr/coursier/tache.md
> +Pour accéder à toutes les informations concernant cette tâches, il existe deux possibilités :
`cette tâches` → `cette tâche`

2019-06-17 16:13 UTC, alexsegura commented on fr/coursier/tache.md
> +- Soit en cliquant sur l'icône ![Liste de tâche](/assets/images/list_icon.png) en bas à droit de l'écran représentant la liste des tâches puis en cliquant sur la tâche désirée.
`à droit` → `à droite`

2019-06-17 16:15 UTC, alexsegura commented on fr/coursier/preuve.md
> +title: Guide du coursier
Title should be "Preuves de livraison" or something like this

2019-06-18 12:17 UTC, alexsegura commented on fr/coursier/livraison.md
> +ref: coursier-home
`ref` should be the same for English & French versions (i.e the same as in file `en/courier/delivery.md`)

2019-06-18 12:17 UTC, alexsegura commented on fr/coursier/preuve-livraison.md
> +ref: coursier-home
`ref` should be different, something like `courier-proof-of-delivery`

2019-06-18 19:10 UTC, alexsegura requested changes

2019-06-18 19:10 UTC, alexsegura commented on _data/sidebar.yml
> +  coursier:
Should be `courier`

2019-06-18 19:41 UTC, arnomasson commented
je check ca

On Tue, Jun 18, 2019 at 9:10 PM Alexandre Segura <notifications@github.com>
wrote:

> *@alexsegura* requested changes on this pull request.
> ------------------------------
>
> In _data/sidebar.yml
> <https://github.com/coopcycle/coopcycle-docs/pull/10#discussion_r294982596>
> :
>
> >    restaurant:
>        - title: Commandes
>          url: /fr/restaurateur/commandes.html
>    dev:
>      - title: API
>        url: /fr/developpeur/api.html
> +  coursier:
>
> Should be courier
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/coopcycle/coopcycle-docs/pull/10?email_source=notifications&email_token=AHS2YI4RSYQOP6EUU7PPCBTP3EXKBA5CNFSM4HYYDU7KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB35JGKY#pullrequestreview-251302699>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHS2YIZABGO5UHGHKMZFG23P3EXKBANCNFSM4HYYDU7A>
> .
>

2019-06-19 18:07 UTC, alexsegura approved these changes

2019-06-19 18:07 UTC, merged